# Generated by Django 2.0.7 on 2018-08-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('topic', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
