# Generated by Django 2.0.7 on 2018-08-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_leavemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
